### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by username1001** [kennethlumalicay/betterweb#19]
Hey, @kennethlumalicay, I saw your post via linkedin, and would like to help out. I've forked and cloned, but I think a CONTRIBUTING.md would be great, so that I, and others, can be consistent with the code. 

Perhaps some instructions on getting everything up and running would be beneficial as well. e.g. fork, clone, npm install, etc. :smiley:

**Comment by username1001** [comment]
Oops, I should have read the issues first. :confused:

**Comment by kennethlumalicay** [comment]
Thanks!
