### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by KBPsystem777** [kennethlumalicay/betterweb#2]
I recently registered here but forgot my `password`. I cant see any forgot password feature around, maybe we can work this out? Thanks :)

**Comment by kennethlumalicay** [comment]
Saw you comment on betterweb. Do you still need help regarding this? Do you have an email associated to the account?

**Comment by KBPsystem777** [comment]
I have an email linked to it and I think I liked my new user account for now :) I just raised this for some other users who is and who would experience it soon.

**Comment by kennethlumalicay** [comment]
I could give you a new password manually and send it to the email linked to it, what is the username/email? 👍

**Comment by KBPsystem777** [comment]
Thanks thanks the email for that is koleen.bp@outlook.com :+1:

**Comment by kennethlumalicay** [comment]
Sent the email! I'll close this for now as the forgot password feature is already on todo list! 😄

**Comment by KBPsystem777** [comment]
@kennethlumalicay I just reset my password. In addition to this, I think the current ui/process in changing passwords is not so catchy so I believe this needs to be improved in a more user-friendly way :)

**Comment by kennethlumalicay** [comment]
Created a new one #8
